# Generated by Django 3.2.9 on 2021-11-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0003_rename_base_sdate_createinvest_base_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createinvest',
            name='base_value',
        ),
    ]
