# Generated by Django 3.2.9 on 2021-11-16 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investment', '0005_createinvest_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='createinvest',
            name='member',
            field=models.ManyToManyField(related_name='invest', to=settings.AUTH_USER_MODEL),
        ),
    ]
