# Generated by Django 3.2.9 on 2021-11-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0011_alter_resultinvest_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='createinvest',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
