# Generated by Django 3.2.9 on 2021-11-24 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0014_auto_20211124_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultinvest',
            name='create_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
