# Generated by Django 3.2.9 on 2021-11-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_purchaseoption_token_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseoption',
            name='token_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
