# Generated by Django 3.2.9 on 2021-11-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_purchaseoption_token_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseoption',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
