# Generated by Django 3.2.9 on 2021-11-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_paymenttransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
