# Generated by Django 3.2.9 on 2021-11-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_remove_createinvest_base_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='createinvest',
            name='description',
            field=models.TextField(max_length=2500, null=True),
        ),
    ]
