# Generated by Django 3.2.9 on 2021-11-16 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investment', '0006_createinvest_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createinvest',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='invest', to=settings.AUTH_USER_MODEL),
        ),
    ]
