# Generated by Django 3.2.9 on 2021-11-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0008_createinvest_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='createinvest',
            name='analysis',
            field=models.TextField(default='', max_length=3000),
        ),
        migrations.AlterField(
            model_name='createinvest',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
