# Generated by Django 3.2.9 on 2021-11-24 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0012_createinvest_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultinvest',
            name='ratio',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultinvest',
            name='total_value',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=14),
            preserve_default=False,
        ),
    ]
