# Generated by Django 3.2.9 on 2021-11-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0013_auto_20211124_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultinvest',
            name='ratio',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='resultinvest',
            name='total_value',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=14),
        ),
    ]
