# Generated by Django 3.2.9 on 2021-11-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_purchaseoption_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseoption',
            name='description',
            field=models.TextField(default='', max_length=500),
        ),
    ]
