# Generated by Django 3.2.9 on 2021-11-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_purchaseoption_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='braintree_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
