# Generated by Django 3.2.9 on 2021-11-18 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_userwallet_braintree_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='braintree_id',
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Buy', 'Buying Transactions'), ('Sell', 'Selling Transactions')], max_length=10)),
                ('braintree_id', models.CharField(blank=True, max_length=150)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payment.userwallet')),
            ],
        ),
    ]
