# Generated by Django 3.2.9 on 2021-11-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(max_length=2500, null=True),
        ),
    ]
